method: random
parameters:
  model_name:
    values:
      - xgboost
      - lightgbm
  learning_rate:
    distribution: uniform
    min: 0.001
    max: 0.1
  max_depth:
    distribution: int_uniform
    min: 3
    max: 10
  n_estimators:
    distribution: q_log_uniform_values
    min: 30
    max: 300
  gamma:
    distribution: uniform
    min: 0.0
    max: 1.0
  num_leaves:
    distribution: int_uniform
    min: 10
    max: 100
  colsample_bytree:
    distribution: uniform
    min: 0.0
    max: 1.0
  subsample:
    distribution: uniform
    min: 0.0
    max: 1.0
  subsample_freq:
    distribution: int_uniform
    min: 3
    max: 10

